import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Chat from './chat'
import ChatProvider, { ChatContext } from '../context/chatContext'
import Login from './login'
import { useContext, useEffect, useState } from 'react'
import axios from 'axios'

const Home: NextPage = () => {
  const [login, setLogin] = useState<boolean>(false)
  const {state, setMainUser} = useContext(ChatContext);

    useEffect(() => {
      axios
        .get('http://localhost:5000/users/me', { withCredentials: true })
        .then((res) => {
          if (res.status === 200)
          { 
            setMainUser({...res.data});
            // setLogin(true);
          }
          else setLogin(false);
        })
    }, [])

    useEffect(() => {
      console.log("state : ", state);
      if (state.mainUser)
        setLogin(true);
    }, [state])
    


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          {!login && <Login login={login} setLogin={setLogin} />}
          {login && <Chat />}
      </main>
    </div>
  )
}

export default Home
