import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Chat from './chat'
import ChatProvider from '../context/chatContext'
import Login from './login'
import { useState } from 'react'

const Home: NextPage = () => {
  const [login, setLogin] = useState<any>(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ChatProvider>
          {!login && <Login login={login} setLogin={setLogin}/>}
          {login && <Chat />}
        </ChatProvider>
      </main>
    </div>
  )
}

export default Home
